//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goalcc_webapi.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueTableMatch
    {
        public decimal LeagueTableMatchId { get; set; }
        public decimal LeagueTableCompetitorId { get; set; }
        public short Played { get; set; }
        public short Won { get; set; }
        public short Draws { get; set; }
        public short Lost { get; set; }
        public short Scored { get; set; }
        public short Conceded { get; set; }
        public short Difference { get; set; }
        public short Points { get; set; }
        public string Type { get; set; }
        public byte[] change_stamp { get; set; }
        public Nullable<short> WinOT { get; set; }
        public Nullable<short> WinPen { get; set; }
        public Nullable<short> LostOT { get; set; }
        public Nullable<short> LostPen { get; set; }
    
        public virtual LeagueTableCompetitor LeagueTableCompetitor { get; set; }
    }
}
