//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goalcc_webapi.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeagueTable()
        {
            this.LeagueTableCompetitors = new HashSet<LeagueTableCompetitor>();
        }
    
        public int LeagueTableId { get; set; }
        public int ContestGroupId { get; set; }
        public short SeasonId { get; set; }
        public Nullable<bool> AutoCalculate { get; set; }
        public byte[] change_stamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeagueTableCompetitor> LeagueTableCompetitors { get; set; }
        public virtual ContestGroup ContestGroup { get; set; }
    }
}
