//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goalcc_webapi.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueTableCompetitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeagueTableCompetitor()
        {
            this.LeagueTableMatches = new HashSet<LeagueTableMatch>();
        }
    
        public decimal LeagueTableCompetitorId { get; set; }
        public int LeagueTableId { get; set; }
        public int TeamId { get; set; }
        public short Place { get; set; }
        public Nullable<int> PointsAdjustment { get; set; }
        public byte[] change_stamp { get; set; }
    
        public virtual LeagueTable LeagueTable { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeagueTableMatch> LeagueTableMatches { get; set; }
    }
}
