//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goalcc_webapi.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsDataPanelEntities : DbContext
    {
        public SportsDataPanelEntities()
            : base("name=SportsDataPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<LeagueTableCompetitor> LeagueTableCompetitors { get; set; }
        public virtual DbSet<LeagueTableMatch> LeagueTableMatches { get; set; }
        public virtual DbSet<LeagueTable> LeagueTables { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<ContestGroup> ContestGroups { get; set; }
    }
}
