//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goalcc_webapi.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.LeagueTableCompetitors = new HashSet<LeagueTableCompetitor>();
        }
    
        public int TeamId { get; set; }
        public Nullable<long> SystemId { get; set; }
        public short SportId { get; set; }
        public Nullable<short> CountryId { get; set; }
        public short GenderId { get; set; }
        public string TeamName { get; set; }
        public string TeamCode { get; set; }
        public string TeamShortName { get; set; }
        public string MobileShortName { get; set; }
        public bool IsNationalTeam { get; set; }
        public string TeamNameEnglish { get; set; }
        public string TeamNameDanish { get; set; }
        public string TeamNameNorwegian { get; set; }
        public string TeamNameSwedish { get; set; }
        public string TeamNameDeutsch { get; set; }
        public string TeamNameItalian { get; set; }
        public string TeamNameSpanish { get; set; }
        public string TeamNameSerbian { get; set; }
        public string SportCCTeamId { get; set; }
        public Nullable<int> OddsDBTeamId { get; set; }
        public string TeamImage { get; set; }
        public string FlashScoresTeamName { get; set; }
        public string SportingLifeTeamName { get; set; }
        public Nullable<long> SoccerwayTeamId { get; set; }
        public string CreatedByRole { get; set; }
        public string SquadLink { get; set; }
        public Nullable<int> SharkScoresId { get; set; }
        public string SharkScoresSquadLink { get; set; }
        public string Bet365TeamName { get; set; }
        public string Bet10TeamName { get; set; }
        public string BetBrightTeamName { get; set; }
        public string BetAtHomeTeamName { get; set; }
        public string BetClicTeamName { get; set; }
        public string BetVictorTeamName { get; set; }
        public string BetWayTeamName { get; set; }
        public string BetCoralTeamName { get; set; }
        public string InterWettenTeamName { get; set; }
        public string LadBrokesTeamName { get; set; }
        public string MyBetTeamName { get; set; }
        public string UniBetTeamName { get; set; }
        public string WinnerTeamName { get; set; }
        public string YouWinTeamName { get; set; }
        public string BetFairTeamName { get; set; }
        public Nullable<int> LiveScoreTeamId { get; set; }
        public string GoalShowTeamId { get; set; }
        public string TitanBetTeamName { get; set; }
        public string StatsComTeamId { get; set; }
        public byte[] change_stamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeagueTableCompetitor> LeagueTableCompetitors { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
